### ISSUE TITLE
Add support for WorldGuard 6.X, used by 1.8-1.12 

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [DrkMatr1984/Piggyback#16]
this is the error i have when i try to run the plugin on 1.12.2 server
```
[00:03:08] [Server thread/INFO]: [PiggyBack] Loading PiggyBack v2.4
[00:03:08] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_12_R1.CraftServer] com/sk89q/worldguard/WorldGuard initializing PiggyBack v2.4 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
	at me.blubdalegend.piggyback.compatibility.WorldGuardHook.<init>(WorldGuardHook.java:21) ~[?:?]
	at me.blubdalegend.piggyback.Piggyback.onLoad(Piggyback.java:96) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:326) ~[dionysus-1.12.2.jar:git-Dionysus-"8d3095e"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:226) ~[dionysus-1.12.2.jar:git-Dionysus-"8d3095e"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:630) ~[dionysus-1.12.2.jar:git-Dionysus-"8d3095e"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159) ~[dionysus-1.12.2.jar:git-Dionysus-"8d3095e"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:107) ~[dionysus-1.12.2.jar:git-Dionysus-"8d3095e"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 6 more
```

Thank you in advance, i am here to test when/if you fix it

**Comment by DrkMatr1984** [comment]
I got a huge update that is halfway cooked up. I'll try to get it released shortly and the worldguard support is fixed in it.

**Comment by DrkMatr1984** [comment]
Just noticed you need 1.12.2. Newest version is for newer servers only But I can compile you a special version for 1.12.2 ;)

**Comment by MotikaCraft-TheJoshua** [comment]
> I got a huge update that is halfway cooked up. I'll try to get it released shortly and the worldguard support is fixed in it.

> Just noticed you need 1.12.2. Newest version is for newer servers only But I can compile you a special version for 1.12.2 ;)

when?
